
CREATE TABLE `o2o`.`tb_shop` (
  `shop_id` int(10) NOT NULL AUTO_INCREMENT COMMENT '店铺ID',
  `owner_id` int(10) NOT NULL COMMENT '店铺创建人',
  `area_id` int(5) DEFAULT null COMMENT '店铺区域ID',
  `shop_category_id` int(11) DEFAULT null COMMENT '店铺类别ID',
  `parent_category_id` int(11) DEFAULT null COMMENT '上级店铺类别ID',
  `shop_name` varchar(256)  NOT null COMMENT '店铺名',
  `shop_desc` varchar(1024) DEFAULT null COMMENT '店铺描述',
  `shop_addr` varchar(200)  DEFAULT null COMMENT '店铺地址',
  `phone` varchar(128)  DEFAULT null COMMENT '联系电话',
  `shop_img` varchar(1024)  DEFAULT null COMMENT '店铺图片',
  `longitude` double(16,12) DEFAULT null COMMENT '经度',
  `latitude` double(16,12) DEFAULT null COMMENT '纬度',
  `priority` int(3) DEFAULT '0' COMMENT '权重',
  `create_time` datetime DEFAULT null COMMENT '创建时间',
  `last_edit_time` datetime DEFAULT null COMMENT '修改时间',
  `enable_status` int(2) NOT NULL DEFAULT '0' COMMENT '店铺状态',
  `advice` varchar(255)  DEFAULT null COMMENT '超级管理员给店家的提醒',
  PRIMARY KEY (`shop_id`),
  KEY `fk_shop_profile` (`owner_id`),
  KEY `fk_shop_area` (`area_id`), 
  KEY `fk_shop_shopcate` (`shop_category_id`),
  KEY `fk_shop_parentcate` (`parent_category_id`),
  CONSTRAINT `fk_shop_area` FOREIGN KEY (`area_id`) REFERENCES `tb_area` (`area_id`),
  CONSTRAINT `fk_shop_parentcate` FOREIGN KEY (`parent_category_id`) REFERENCES `tb_shop_category` (`shop_category_id`),
  CONSTRAINT `fk_shop_profile` FOREIGN KEY (`owner_id`) REFERENCES `tb_person_info` (`user_id`),
  CONSTRAINT `fk_shop_shopcate` FOREIGN KEY (`shop_category_id`) REFERENCES `tb_shop_category` (`shop_category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ;